server:
  servlet:
    context-path: /
  port: 8099

spring:
  application:
    name: treeholecore


  # \u70ED\u90E8\u7F72\u751F\u6548
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/treehole?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      #\u6700\u5927\u8FDE\u63A5\u6570
      maximum-pool-size: 10
      #\u4ECE\u8FDE\u63A5\u6C60\u8FD4\u56DE\u7684\u8FDE\u63A5\u7684\u81EA\u52A8\u63D0\u4EA4
      auto-commit: true
      #\u8FDE\u63A5\u6700\u5927\u5B58\u6D3B\u65F6\u95F4
      max-lifetime: 180000
      #\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
      connection-timeout: 30000
      #\u6D4B\u8BD5\u8FDE\u63A5\u53EF\u67E5\u8BE2\u8BED\u53E5
      connection-test-query: SELECT 1



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: net.com.treehole.treeholecore.entity


#logging
logging:
  config: classpath:log/logback.xml