DROP TABLE IF EXISTS TREEHOLE_USER;
CREATE TABLE TREEHOLE_USER(
    USER_ID BIGINT(32) NOT NULL   COMMENT '用户ID' ,
    USER_UUID BIGINT(32)    COMMENT 'UUID' ,
    TENANT_ID VARCHAR(255)    COMMENT '租户号' ,
    REVISION VARCHAR(255)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(255)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(255)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    USER_NAME VARCHAR(255)    COMMENT '用户名称' ,
    DEL_STATUS INT    COMMENT '删除标识符默认0删除1' ,
    PRIMARY KEY (USER_ID)
)  COMMENT = '用户信息表';


CREATE INDEX USER_NAME ON TREEHOLE_USER(USER_NAME);

DROP TABLE IF EXISTS TREEHOLE_CHAT;
CREATE TABLE TREEHOLE_CHAT(
    CHAT_ID BIGINT(32) NOT NULL   COMMENT 'CHARID' ,
    USER_ID BIGINT(32)    COMMENT '用户ID' ,
    ANOTHER_ID BIGINT(32)    COMMENT '对方ID' ,
    TENANT_ID VARCHAR(32)    COMMENT '租户号' ,
    REVISION VARCHAR(255)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(255)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(255)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DEL_STATUS INT    COMMENT '删除标识符默认0删除1' ,
    PRIMARY KEY (CHAT_ID)
)  COMMENT = '聊天主表';

DROP TABLE IF EXISTS TREEHOLE_CHAT_COMMUNICATION;
CREATE TABLE TREEHOLE_CHAT_COMMUNICATION(
    COMMUNICATION_ID BIGINT(32) NOT NULL   COMMENT '聊天消息ID' ,
    FROM_ID BIGINT(32)    COMMENT '发送人ID' ,
    FROM_NAME VARCHAR(255)    COMMENT '发送人NAME' ,
    TO_ID BIGINT(32)    COMMENT '接收人ID' ,
    TO_NAME VARCHAR(900)    COMMENT '接收人NAME' ,
    CONTENT TEXT NOT NULL   COMMENT '消息内容' ,
    GROUP_ID BIGINT(32)    COMMENT '群ID' ,
    GROUP_NAME VARCHAR(255)    COMMENT '群NAME' ,
    READ_STATUS INT    COMMENT '是否已读,不适用于群消息' ,
    CLASS INT    COMMENT '消息类：1是用户聊天，2是群组聊天' ,
    TYPE INT    COMMENT '消息类型：1是普通文本，2是图片，3是语音' ,
    CHAT_ID BIGINT(32)    COMMENT '聊天主表ID' ,
    TENANT_ID VARCHAR(255)    COMMENT '租户号' ,
    REVISION VARCHAR(255)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(255)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(32)    COMMENT '更新人' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    DEL_STATUS INT    COMMENT '删除标识符默认0删除1' ,
    PRIMARY KEY (COMMUNICATION_ID)
)  COMMENT = '聊天消息表';

DROP TABLE IF EXISTS TREEHOLE_USER_FRIENDS;
CREATE TABLE TREEHOLE_USER_FRIENDS(
    FRIENDS_ID BIGINT(32)    COMMENT '好友表ID' ,
    FROM_ID BIGINT(32)    COMMENT '用户ID' ,
    TO_ID BIGINT(32)    COMMENT '好友ID' ,
    NOTE_NAME VARCHAR(255)    COMMENT '好友备注' ,
    UPDATED_TIME DATETIME    COMMENT '更新时间' ,
    TENANT_ID VARCHAR(255)    COMMENT '租户号' ,
    REVISION VARCHAR(255)    COMMENT '乐观锁' ,
    CREATED_BY VARCHAR(255)    COMMENT '创建人' ,
    CREATED_TIME DATETIME    COMMENT '创建时间' ,
    UPDATED_BY VARCHAR(255)    COMMENT '更新人' ,
    DEL_STATUS INT    COMMENT '删除标识符默认0删除1' 
)  COMMENT = '好友表';

